### ISSUE TITLE
Error: No property title on Gjs_ui_AttachedToBatteryView_AttachedToBatteryToggle

### ISSUE THREAD

**Issue by sjanofsky** [LorenzoMorelli/GPU_profile_selector#11]
Getting this error in Fedora 37/GNOME 43.5 and extension won't load.

Envycontrol is installed globally.

**Comment by ARYN-27** [comment]
Same error is EndeavorOS/GNOME  43.4

![image](https://user-images.githubusercontent.com/53664593/232197346-2af0e698-33a3-45b7-8521-9a68a66135e4.png)

**Comment by davipro34** [comment]
Same error is Manjaro OS / GNOME 43.4 / Xorg

**Comment by Lama96103** [comment]
I have same error on Fedora 37, Gnome 43.4, Xorg

`
JS ERROR: Extension GPU_profile_selector@lorenzo9904.gmail.com: Error: No property title on Gjs_ui_AttachedToBatteryView_AttachedToBatteryToggle
_init@resource:///org/gnome/shell/ui/quickSettings.js:23:15
_init@resource:///org/gnome/shell/ui/quickSettings.js:45:15
_init@resource:///org/gnome/shell/ui/quickSettings.js:105:15
_init@/home/lars/.local/share/gnome-shell/extensions/GPU_profile_selector@lorenzo9904.gmail.com/ui/AttachedToBatteryView.js:27:15
QuickSettingsItem@resource:///org/gnome/shell/ui/quickSettings.js:21:4
QuickToggle@resource:///org/gnome/shell/ui/quickSettings.js:43:4
QuickMenuToggle@resource:///org/gnome/shell/ui/quickSettings.js:103:4
AttachedToBatteryToggle@/home/lars/.local/share/gnome-shell/extensions/GPU_profile_selector@lorenzo9904.gmail.com/ui/AttachedToBatteryView.js:22:9
_init@/home/lars/.local/share/gnome-shell/extensions/GPU_profile_selector@lorenzo9904.gmail.com/ui/AttachedToBatteryView.js:80:38
SystemIndicator@resource:///org/gnome/shell/ui/quickSettings.js:692:1
AttachedToBatteryView@/home/lars/.local/share/gnome-shell/extensions/GPU_profile_selector@lorenzo9904.gmail.com/ui/AttachedToBatteryView.js:70:1
getAttachedToBatteryView@/home/lars/.local/share/gnome-shell/extensions/GPU_profile_selector@lorenzo9904.gmail.com/ui/AttachedToBatteryView.js:95:12
enable@/home/lars/.local/share/gnome-shell/extensions/GPU_profile_selector@lorenzo9904.gmail.com/extension.js:23:56
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:184:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:385:26
_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:267:35
Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:130:41
`

**Comment by LorenzoMorelli** [comment]
Hi all. Thank you for reporting this issue, I'm going to fix it as soon as possible. In the meanwhile, if you need you could use the old version (14).

**Comment by LorenzoMorelli** [comment]
Gnome 43 unfortunately doesn't support the new extension updates. So now I should have fixed the issue by setting the 15 version of the extension to be compatible only with gnome 44. If you still have the issue, then uninstall and reinstall the extension from the Gnome extension store or install manually the right one (version 14 for gnome 43) from github releases. I'm going to wait some days before closing this issue. If there will not be any comment, I will close this issue. Let me know.
