### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [LorenzoMorelli/GPU_profile_selector#12]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by Boria138** [comment]
> 

Could you please check this pr 
https://github.com/LorenzoMorelli/GPU_profile_selector/pull/14

**Comment by LorenzoMorelli** [comment]
Hi! I want to thank you for your support with PR. Unfortunately I'm a bit busy in this period :(

**Comment by Boria138** [comment]
> Hi! I want to thank you for your support with PR. Unfortunately I'm a bit busy in this period :(

As I wrote pr is not fully ready yet, as I have not yet put myself gnome 45 for testing, so I guess by the time everything will be ready you will be free (by then I will close this pr and open a new one so as not to breed unnecessary comites in the main thread)

**Comment by federicotorrielli** [comment]
Any updates on this?

**Comment by LorenzoMorelli** [comment]
Hi Federico, @Boria138 is working on the porting to Gnome 45 and he did a very nice job. Unfortunately a lot of things changed from Gnome 44 making this porting really time consuming. In these days, I'm going to test his work. In the meanwhile, you can test his fork by yourself at [https://github.com/Boria138/GPU_profile_selector](https://github.com/Boria138/GPU_profile_selector)

**Comment by LorenzoMorelli** [comment]
Enjoy the new Gnome 45 release!
