### ISSUE TITLE
Globally installed envycontrol dependency on Ubuntu 22.04

### ISSUE THREAD

**Issue by danielbellsa** [LorenzoMorelli/GPU_profile_selector#2]
Is GPU_profile_selector compatible with **Ubuntu 22.04**?

I've installed all dependencies from both [envycontrol](https://github.com/geminis3/envycontrol) and [GPU_profile_selector](https://github.com/LorenzoMorelli/GPU_profile_selector) and rebooted without it seeing the graphic interface extension ;(

**Comment by LorenzoMorelli** [comment]
Hi, first of all thanks, the exams were great!
I tried to focus on your possible problem, I sow the EnvyControl developer have posted a note regarding Ubuntu. I don't know if you have already seen that, so when in doubt I post the link below, let me know.

https://github.com/geminis3/envycontrol/wiki/Frequently-Asked-Questions#a-note-for-ubuntu-users
