### ISSUE TITLE
Please consider adding GNOME 46 support

### ISSUE THREAD

**Issue by szw0407** [LorenzoMorelli/GPU_profile_selector#20]
GNOME 46 has been released and multiple systems including openSUSE tumbleweed has upgraded GNOME to this version. This extension is not loaded.

Please consider adding support for GNOME 46.

**Comment by LorenzoMorelli** [comment]
Hi, I'm working on it right now!

**Comment by realKarthikNair** [comment]
It apparently is working just by changing metadata.json

```bash
sed -i 's/"shell-version": \[/&\n    "46",/' $HOME/.local/share/gnome-shell/extensions/GPU_profile_selector@lorenzo9904.gmail.com/metadata.json
```

should do the job for now

```bash
karthik@fedora:~$ cat $HOME/.local/share/gnome-shell/extensions/GPU_profile_selector@lorenzo9904.gmail.com/metadata.json 
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "You need to install envycontrol(https://github.com/geminis3/envycontrol) to make this extension work. This is a simple gnome-shell extension which provides a simple way to switch between GPU profiles on Nvidia Optimus systems (i.e laptops with Intel + Nvidia or AMD + Nvidia configurations) in a few clicks.",
  "gettext-domain": "GPU_profile_selector",
  "name": "GPU profile selector",
  "settings-schema": "org.gnome.shell.extensions.GPU_profile_selector",
  "shell-version": [
    "45",
    "46"
  ],
  "url": "https://github.com/LorenzoMorelli/GPU_profile_selector",
  "uuid": "GPU_profile_selector@lorenzo9904.gmail.com",
  "version": 18
}
```

**Comment by yochananmarqos** [comment]
No comma is required:

```
sed -i 's/"45"/"45"\n\    "46"/g'
```

```
  "shell-version": [
    "45"
    "46"
  ],
```

**Comment by LorenzoMorelli** [comment]
Thank you for testing it out! I'm going to test it out and prepare a new release soon

**Comment by l3ifk** [comment]
Can confirm that it does work for me too with this config.

**Comment by LorenzoMorelli** [comment]
Hi all, I've finally checked all the extension flows in gnome 46. I can confirm gnome 46 doesn't introduce any breaking changes and it was only a matter of adding 46 to supported shell version in metadata.json. I want to really thank you all for your feedbacks! The repository is now up to date and the extension is in the reviewing phase on gnome extension website.

**Comment by realKarthikNair** [comment]
Thanks
