### ISSUE TITLE
Visual consistency with the rest of the quick settings

### ISSUE THREAD

**Issue by not-a-dev-stein** [LorenzoMorelli/GPU_profile_selector#3]
A small issue, not a particular priority, but it'd be nice if the visual indicator of the current selected GPU used the same indicator as the rest of the quick settings menu. Here's an example of how it looks on the power-profiles-daemon section:

![image](https://user-images.githubusercontent.com/63420929/173260940-9dbd1e98-66d6-469d-bd84-bb3880ef48d2.png)

...compared to how it is used by the extension:

![image](https://user-images.githubusercontent.com/63420929/173261117-acfd8fbf-9a99-48b8-b880-3ca95aa8d3a3.png)

I'm not sure how much work would be needed to use it for such a small benefit in visual consistency, so I don't expect it to be treated as a priority ever, but it would be a nice to have if it doesn't take too much work to do so.

**Comment by LorenzoMorelli** [comment]
Of course, it is surely something which will be implemented. Thanks you for the advice!

**Comment by Scotty-Trees** [comment]
![Screenshot from 2022-07-01 14-50-54](https://user-images.githubusercontent.com/45135187/176954045-2b6b8450-b960-498c-b9bf-64966444a86d.png)

There was a new GPU Profile extension update today to version 8, which fixes this as the screenshot above shows. This issues can be closed now I think. Keep up the good work on the extension, EnvyControl is so good!

**Comment by LorenzoMorelli** [comment]
Thanks you so much!
