### ISSUE TITLE
Broken on gnome 43

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [LorenzoMorelli/GPU_profile_selector#8]
I tried to get it running on gnome 43 with some modification I got something usable but I have broken retro-compatibility and no icons work. Still, this can be interesting if you plan to port it properly.

Edit: by "port it properly" i meant not like what I did.

[gnome43_test.zip](https://github.com/LorenzoMorelli/GPU_profile_selector/files/9722031/gnome43_test.zip)

**Comment by ActualDisaster2447** [comment]
I hope this extension gets ported to GNOME 43. As it seems to me (not a developer), it might need to be rewritten completely with how much the quick settings have changed.

**Comment by LorenzoMorelli** [comment]
Hi, first of all thank you for your help and suggestion!
Of course I have planned to port the extension to the new Gnome version.
As far as I know Gnome 43 is not released yet, but for sure when I'll update my system I'm going to port this extension for gnome 43!!

**Comment by Marc-Pierre-Barbier** [comment]
it is released but most distribution have yet to shitp with it.

i think the first to do this will be fedora 37

**Comment by pushkargogte** [comment]
@Marc-Pierre-Barbier gnome43 is released and also ships with ubuntu 22.10

**Comment by ActualDisaster2447** [comment]
Tumbleweed already has it and Fedora is getting it soon (once 37 is out in a few days).

**Comment by Marc-Pierre-Barbier** [comment]
Ok we get it guys. In the meantime, if you want something that """just works""" use "gnome43_test.zip" (the first comment) and extract it in ~/.local/share/gnome-shell/extensions. It's a dirty patch and all the logos are broken. But the basic functionalities are there.

**Comment by LorenzoMorelli** [comment]
Exactly, The distro I'm using (arch), unfortunately doesn't have got this update yet, so I cannot test the whole extension on my computer. I need to wait for my system getting gnome update in order to start working on it. I'm sorry

**Comment by Marc-Pierre-Barbier** [comment]
im on arch too but im using this unofficial repo: https://gitlab.com/fabiscafe/gnome-unstable

**Comment by bryce-lynch** [comment]
@LorenzoMorelli v43 is in official arch now

**Comment by LorenzoMorelli** [comment]
Yeah finally! I'm working on update, now I'm a little busy with university so it could take a bit more but I hope it will be ready soon!

**Comment by LorenzoMorelli** [comment]
Hi, yes I just update on main stream a new version compatible with gnome 43.
Minor fix should be done but in the meanwhile the extension now should be perfectly usable.
Once fixed minor thing, I'm going to update also on the gnome extension website.

Regarding EnvyControl it is still working for now. I made this extension for my personal needing and I'm going to maintain this extension until I need it :)
